[env:esp32dev]
platform = espressif32@5.4.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200

; Librerías necesarias
lib_deps = 
    bblanchon/ArduinoJson@^6.21.3
    knolleary/PubSubClient@^2.8

; Configuración de compilación
build_flags = 
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DCONFIG_ARDUINO_USB_CDC_ON_BOOT=0
    -DPLATFORMIO=1
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections

; Configuración de monitor
monitor_filters = 
    default
    time